language: node_js
node_js:
  - "8.12.0"

dist: trusty
sudo: false

addons:
  apt:
    packages:
      - sshpass

before_script:
  - npm install -g gatsby-cli
script:
  - npm install
  - npm run build

deploy:
  skip_cleanup: true
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
