language: node_js
node_js:
  - "8.12.0"

dist: trusty
sudo: false

addons:
  apt:
    packages:
      - sshpass

before_script:
  - npm install -g gatsby-cli
script:
  - gatsby build

deploy:
  provider: script
  script: sshpass -p ${TRAVIS_PASS} scp -r public/* ${TRAVIS_USER}@wilcoxlab.uw.edu:/opt/wilcoxlab/www/
  on:
    branch: master
