language: node_js
node_js:
  - "8.12.0"

dist: trusty
sudo: false

addons:
  apt:
    packages:
      - sshpass

before_script:
  - npm install -g gatsby-cli
script:
  - gatsby build

deploy:
  skip_cleanup: true
  provider: script
  script: sshpass -e scp -r public/* travis@wilcoxlab.uw.edu:/opt/wilcoxlab/www/
  on:
    branch: master
